AWSTemplateFormatVersion: "2010-09-09"
Description: Mock a pipeline using CodePipeline and Lambda. You will be billed for the AWS resources used if you create a stack from this template.
Parameters:
  S3Bucket:
    Type: String
    Default: stelligent-training-public
  S3Key:
    Type: String
    Default: public/codepipeline/aws-codepipeline-s3-aws-codedeploy_linux.zip
  EmailAddress:
    Type: String
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Params to Modify
        Parameters:
          - EmailAddress
Resources:
  MySNSTopic:
    Type: "AWS::SNS::Topic"
    Properties: 
      DisplayName: String
      Subscription:
        - Endpoint: !Ref EmailAddress
          Protocol: "email"
      TopicName: 
        Ref: AWS::StackName
  WebsiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
  WebsiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: WebsiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal: "*"
          Action: s3:GetObject
          Resource:
            Fn::Join:
              - ""
              - - "arn:aws:s3:::"
                - Ref: WebsiteBucket
                - "/*"
  ArtifactStoreBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled
      AccessControl: BucketOwnerFullControl
  CodePipelineLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codebuild.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
  CodePipelineLambdaDummy:
    Type: "AWS::Lambda::Function"
    DependsOn: [CodePipelineLambdaRole, LambdaCodePipelineExecutionPolicy]
    Properties:
      Code: 
        S3Bucket: !Ref S3Bucket
        S3Key: "Archive.zip" 
      Role: 
        Fn::GetAtt: 
          - "CodePipelineLambdaRole"
          - "Arn"
      Description: "Always return success"
      Timeout: 20
      Handler: lambdadummy.handler
      Runtime: "nodejs4.3"
      MemorySize: 128
  LambdaCodePipelineExecutionPolicy:
    Type: "AWS::IAM::Policy"
    Properties: 
      PolicyName: "LambdaRolePolicy"
      PolicyDocument: 
        Version: "2012-10-17"
        Statement: 
          - 
            Effect: "Allow"
            Action: 
              - "cloudformation:*"
              - "logs:*"
            Resource: "*"
      Roles: 
        - 
          Ref: "CodePipelineLambdaRole"     
  CodePipelineStack:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt [CodePipelineRole, Arn]
      ArtifactStore:
        Location:
          Ref:
            ArtifactStoreBucket
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - InputArtifacts: []
              Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: S3
              OutputArtifacts:
                - Name: MyApp
              Configuration:
                S3Bucket: !Ref S3Bucket
                S3ObjectKey: !Ref S3Key
              RunOrder: 1
        - Name: Commit
          Actions:
            - InputArtifacts: []
              Name: Build
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: 1
                Provider: Lambda
              Configuration:
                FunctionName: !Ref CodePipelineLambdaDummy
                UserParameters: !Ref AWS::StackName
              RunOrder: 1
            - InputArtifacts: []
              Name: StaticAnalysis
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: 1
                Provider: Lambda
              Configuration:
                FunctionName: !Ref CodePipelineLambdaDummy
                UserParameters: !Ref AWS::StackName
              RunOrder: 1
            - InputArtifacts: []
              Name: UnitTest
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: 1
                Provider: Lambda
              Configuration:
                FunctionName: !Ref CodePipelineLambdaDummy
                UserParameters: !Ref AWS::StackName
              RunOrder: 2
        - Name: AcceptanceTesting
          Actions:
            - InputArtifacts: []
              Name: ProvisionEnvironment
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: 1
                Provider: Lambda
              Configuration:
                FunctionName: !Ref CodePipelineLambdaDummy
                UserParameters: !Ref AWS::StackName
              RunOrder: 1
            - InputArtifacts: []
              Name: InfrastructureAnalysis
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: 1
                Provider: Lambda
              Configuration:
                FunctionName: !Ref CodePipelineLambdaDummy
                UserParameters: !Ref AWS::StackName
              RunOrder: 1
            - InputArtifacts: []
              Name: ConfigureEnvironment
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: 1
                Provider: Lambda
              Configuration:
                FunctionName: !Ref CodePipelineLambdaDummy
                UserParameters: !Ref AWS::StackName
              RunOrder: 2
            - InputArtifacts: []
              Name: AcceptanceTests
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: 1
                Provider: Lambda
              Configuration:
                FunctionName: !Ref CodePipelineLambdaDummy
                UserParameters: !Ref AWS::StackName
              RunOrder: 3
            - InputArtifacts: []
              Name: IntegrationTests
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: 1
                Provider: Lambda
              Configuration:
                FunctionName: !Ref CodePipelineLambdaDummy
                UserParameters: !Ref AWS::StackName
              RunOrder: 3
            - InputArtifacts: []
              Name: DeployApp
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: 1
                Provider: Lambda
              Configuration:
                FunctionName: !Ref CodePipelineLambdaDummy
                UserParameters: !Ref AWS::StackName
              RunOrder: 4
            - InputArtifacts: []
              Name: DeploymentTest
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: 1
                Provider: Lambda
              Configuration:
                FunctionName: !Ref CodePipelineLambdaDummy
                UserParameters: !Ref AWS::StackName
              RunOrder: 5
        - Name: Capacity
          Actions:
            - InputArtifacts: []
              Name: PenTest
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: 1
                Provider: Lambda
              Configuration:
                FunctionName: !Ref CodePipelineLambdaDummy
                UserParameters: !Ref AWS::StackName
              RunOrder: 1 
            - InputArtifacts: []
              Name: PerformanceTest
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: 1
                Provider: Lambda
              Configuration:
                FunctionName: !Ref CodePipelineLambdaDummy
                UserParameters: !Ref AWS::StackName
              RunOrder: 1 
            - InputArtifacts: []
              Name: ImageTests
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: 1
                Provider: Lambda
              Configuration:
                FunctionName: !Ref CodePipelineLambdaDummy
                UserParameters: !Ref AWS::StackName
              RunOrder: 1 
            - InputArtifacts: []
              Name: ResiliencyTests
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: 1
                Provider: Lambda
              Configuration:
                FunctionName: !Ref CodePipelineLambdaDummy
                UserParameters: !Ref AWS::StackName
              RunOrder: 1
        - Name: ExploratoryTesting
          Actions:
            - InputArtifacts: []
              Name: QA
              ActionTypeId:
                Category: Approval
                Owner: AWS
                Version: 1
                Provider: Manual
              Configuration:
                NotificationArn:
                  Ref: MySNSTopic
                CustomData: "Approval or Reject this change after running Exploratory Tests"
              RunOrder: 1 
        - Name: Production
          Actions:
            - InputArtifacts: []
              Name: BlueGreenDeployment
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: 1
                Provider: Lambda
              Configuration:
                FunctionName: !Ref CodePipelineLambdaDummy
                UserParameters: !Ref AWS::StackName
              RunOrder: 1 
            - InputArtifacts: []
              Name: OutofBandTests
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: 1
                Provider: Lambda
              Configuration:
                FunctionName: !Ref CodePipelineLambdaDummy
                UserParameters: !Ref AWS::StackName
              RunOrder: 1 
            - InputArtifacts: []
              Name: SecurityMetrics
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: 1
                Provider: Lambda
              Configuration:
                FunctionName: !Ref CodePipelineLambdaDummy
                UserParameters: !Ref AWS::StackName
              RunOrder: 1 
            - InputArtifacts: []
              Name: SwitchEndPoints
              ActionTypeId:
                Category: Invoke
                Owner: AWS
                Version: 1
                Provider: Lambda
              Configuration:
                FunctionName: !Ref CodePipelineLambdaDummy
                UserParameters: !Ref AWS::StackName
              RunOrder: 2                                                           
  CodePipelineRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AdministratorAccess
Outputs:
  CodePipelineURL:
    Description: CodePipeline URL
    Value:
      Fn::Join:
        - ""
        - - "https://console.aws.amazon.com/codepipeline/home?region="
          - Ref: AWS::Region
          - "#/view/"
          - Ref: CodePipelineStack