version: 0.2

phases:
  build:
    commands:
      - npm install
      - aws cloudformation package --template sam-template-notifications.yml --s3-bucket $S3_BUCKET --output-template template-export.json

artifacts:
  type: zip
  files:
    - template-export.json
